{% set name = "aspy.yaml" %}
{% set version = "1.0.0" %}
{% set hash_type = "sha256" %}
{% set hash = "455aa097212c7a435c1d5c99d18cdee80a0e4860f9f41dee86c149c47a95c980" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/asottile/aspy.yaml/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - pyyaml

test:
  imports:
    - aspy
    - aspy.yaml
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: http://github.com/asottile/aspy.yaml
  license: MIT
  summary: 'A few extensions to pyyaml.'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
