{% set name = "aspy.yaml" %}
{% set version = "1.1.2" %}
{% set hash_type = "sha256" %}
{% set hash = "44f3b43fc820ceead6aa52edce43f3b018cdf6e416467a62ecfb9601d61022ea" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/asottile/aspy.yaml/archive/v{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python -m pip install . --no-deps --ignore-installed
  noarch: python

requirements:
  build:
    - pip
    - python
    - setuptools

  run:
    - python
    - pyyaml

test:
  imports:
    - aspy
    - aspy.yaml
  requires:
    - pytest
  source_files:
    - tests
  commands:
    - pytest tests

about:
  home: http://github.com/asottile/aspy.yaml
  license: MIT
  summary: 'A few extensions to pyyaml.'
  license_family: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - nicoddemus
