travis:
  secure:
    BINSTAR_TOKEN: sZPIwOMp3lh1MiUhRXiwiayBrahenFmbKaD800dZCrH/H7YyZh7vXks7GkzHeKMsPNtOLSkPNHPW4d28nH7hqSz1TXWtjsC0hpemOWE3+Y+Egynq1kPAHsZJAQpoD5pH8E34plEcyavT3wQ0XPwwHAv8iokp5p/jdYjSJW8U50Zh3qIX+4pGRWZ5MVE7hwnzD9i7/TRQA0Tw3yV0b/RjOBBOEB+xhhgCWErkvpDbJ6vbGZqMj71uuP5kEsbgWsl8iG7mLYtpq9G3hxRj20FvQdpReSdBs+hMsE8wEFNiZmIhaZaTGdwwHMU2EGYVecwzN26ZQqF9y5nnlr0uB6HUFfTOYv57aYL1mAUSp42CzhF7ROOxOg4vQO/dFVjjCZqXsuccTdNlMrM+Nlbn9xfhK/D8a7LwVU/sBpZNwJaoR8nSKO3fyXgryK9aPX/6AY/6JPAcjdBBROCBeUrn7/Au3trehHnhcCiqi8H5sB39UOIjIg887UE5swedqnP+rLfz2KkuodwynUnrGKV6Ne9qvAFerc3xDd8svHO5aHAp1vnaaHRuQ62K1ubwH3KLzirB3+4NnYkhCTENeKvAUmVn9PFBLtdkphYnNkhaJquPL4h19PaexYPPss9kP09mTFHtFo39Pf5EMQJiRTJtgxz8i5wz6zXSmMHr8FSrNreEmeU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
