travis:
  secure:
    BINSTAR_TOKEN: dbjjJHM7+Va1EZ3mgp8auiWoxXiL6GG38eRZbMEWjtTY8OURBAz8ZAJvwCCyU1s/sSapWNlPkt4XsfcQ7xDKQlqdK6o6WJ8R+VL8aTZKjvA7UzbxdLnqbhuWClgN/BdizN8wO9p8xIAuarw8pzvC21WofLT8NA9tB90RhfgNHE77g9HaOoK8uhX5a4YWX5mf5ws2IAbbsjKMArNR/N1bhMyMPn7ekdooNdey4yFKsXilTlPueMSaT96BY3nYC/F1HzT+pqTPjp0POMLGEi1dggr/s7wFlAxgTEgFppiq1NIy/ZNNxLPkRCFH+FXSqZgJGabryVyMjUl9qE0cE4QCC6/6+M1y4Ot10wXrkiNUX4wpXvRs8DbwMToS79a19KkBK7NfksHE2iKCRkFkU55t/1KyRVpSiYUOA43KSa3hJ6qlVR1bHpw9sFno5pPgBB4S6OwxFlLQDbW4qSF16DFRa3fuOAyKwfRcAgVdPzN49Rgg7mkzqV6e0c42obbvSeXdmpGS7KfCezjiV8jKI6Lm0/ex7fhTV8sJZ9gb1UtoEokQ1B6t0QaD2BR8b+pzrJRGnny6qNRQenD7EFm+tv+60ADcL2WkoW8zj96tvSPAAWM6yBwUzydTGorOP5COVKRnnTlGw6YHmd0P/gmLc4GwJUvrWExwMRJR78vbBN24NLI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
