travis:
  secure:
    BINSTAR_TOKEN: KUTrRnQ2UMUbQ+ZofLVvwp7wYvlC/fhoXpjgLYurtLiXvOeACF1Q3qnQHVa/3xJmqCIkkraYTr5fpa+d0juOs2J5EeKh7CKK28qor/Su9G1uAgna3ett+3IT1AQYBNpHXDWtFvpXq0H6xrmluaVU5PcFqZjHd8KzG0t8HzMTCTOvYC+xB8IbPR6QXDu9nsCXhG9cE/01iXj/ExVhephQICkHxVrtvPeQvcRj8TrUBnAAI2Oos2U1QKk/dnnRMKh2qjY2qXCNyAXKhe9IrEW/NBx2Zu1KbWkmjxrvCk1HqKl68aD6H/QAmFwXjLqLRfXViIuzx1DvVnJEr918txnVLRjgcG1UwAkErdU2cO4v+C9LNOG7R7DzEdY3ENLjfwmrvoZZ1j/9blIEKodo773/og2efXXXrrOE5sbeHUbxKS40gwgw+e5A90D1F0Dxq8pp7iaAybvSW6R30M8fJAvmYyUj3nlOULdyGfvgLDEFrwrplyOaeb/lMg5nM+DAAj4TTpjsbd3E/jIIPZS4KJJXbHpkfa5RcTbJCoIdRtswF2oNu6Noa/Tgj4jcrKzRo4WOsuFaBPWMJU4ypyUCziwgRMhz+pmz6m/y0zs77xsonzAS8HmfcfjbHHv/uHY5UjVIlM9vQM3jXNSCFcmIVI7M6xF21uYtrvsLjBDk5C1vpdU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
